#开启sentinel对feign的支持
#feign.sentinel.enabled: true
spring:
  zipkin:
    base-url: http://192.168.105.71:9411/
    sender.type: web
  #采样比例默认的为 0.1可设置介于 0到 1之间，1则表示全部采集
  sleuth.sampler.probability: 0.1
