spring:
  cloud:
    sentinel:
      # 取消Sentinel控制台懒加载
      eager: true
      transport:
        # 本地应用与Sentinel控制台交互的端口
        port: 8719
        # Sentinel 控制台地址
        dashboard: 192.168.105.71:8080
      filter:
        # Enable to instance CommonFilter
        enabled: true
      datasource.ds1.file:
        file: "classpath: gw-api-group.json"
        ruleType: gw-api-group
      datasource.ds2.file:
        file: "classpath: flow.json"
        ruleType: flow #gw-flow
      datasource.ds3.file:
        file: "classpath: degrade.json"
        ruleType: degrade
        data-type: json

  redis:
    host: 127.0.0.1
    port: 6371
